### ISSUE TITLE
Perl dependencies are all in Debian

### ISSUE THREAD

**Issue by d-torrance** [aubreyja/ww_install#94]
While working on the Debian WeBWorK package, I have been using ww_install's install_prerequisites.sh script as a reference for the needed dependencies.

I discovered that many of the Perl dependencies which ww_install downloads from CPAN are now actually in Debian.  There were still two missing -- XML::Parser::EasyTree and Array::Utils. I have packaged those and they were just accepted into Debian unstable.

Note that, depending on which version of Debian (or a derivative like Ubuntu) is being used, these packages may or may not be available.  So perhaps it's best to keep ww_install as it is for a while.

**Comment by goehle** [comment]
The newst (beta) version of ww_install does prerequisites differently.  They are now all version specific so we can use the appropriate debian packages if they are present and download them from CPAN if they aren't.  

See the distros folder for specifics

https://github.com/goehle/ww_install/tree/release2.11
