### ISSUE TITLE
Installation on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by paultpearson** [aubreyja/ww_install#95]
I tried installing webwork using the ww_install.sh script, but it did not run to completion.  I have attached the output log (which was not automatically written to a file).  There is nothing in the /opt directory, so the installation was definitely unsuccessful.

[webwork_install_log.txt](https://github.com/aubreyja/ww_install/files/386598/webwork_install_log.txt)

**Comment by aubreyja** [comment]
Hi Paul,

Did you try the version at the openwebwork repo? It's more up to date
thanks to Geoff.

Jason

**Comment by paultpearson** [comment]
For completeness, I'll post our email discussion here.

The installation script from the openwebwork repo worked.

The README.md file 

https://github.com/openwebwork/ww_install/README.md

needs to be updated to say

wget --no-check-certificate https://raw.githubusercontent.com/openwebwork/ww_install/master/install_webwork.sh
curl -ksSO https://raw.githubusercontent.com/openwebwork/ww_install/master/install_webwork.sh

Note that it is now githubusercontent.com and not github.com.  Also, you might want to update the https://github.com/aubreyja/ww_install/README.md for your personal github repo for this to say that it is out of date and that users should instead go to the openwebwork repo at https://github.com/openwebwork/ww_install.
